name: esc_pos_printer
publish_to: none
description: The library allows to print receipts using an ESC/POS thermal WiFi printer.
version: 4.1.0
homepage: https://github.com/andrey-ushakov/esc_pos_printer

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  charset_converter: ^2.1.1
  esc_pos_utils:
#    path: /Users/lysandergustin/Projects/AndroidStudioProjects/esc_pos_utils
      git:
        url: https://github.com/rainbowMehBerdaya/esc_pos_utils.git
        ref: afcc61a40eacd3bd49d9df48e210dfe1ba62e42b
  flutter:
    sdk: flutter
  # esc_pos_utils:
  #   path: ../esc_pos_utils
  image: ^4.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
